version: "3.9"
services:
  client:
    build: ./client
    depends_on:
      - server

  server:
    build: ./server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://prisma:prisma@todos-production-db:5432/todos

  db:
    image: postgres:13
    container_name: todos-production-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: todos
