version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "8000:8000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000" 
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://prisma:prisma@tasks-production-db:5432/tasks

  db:
    image: postgres:13
    container_name: tasks-production-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tasks
