version: "3.9"

services:
  db:
    image: postgres:13
    container_name: tasks-development-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tasks
